version: "3"
services: 
  db:
      build:
        context: ./db
        dockerfile: postgres.Dockerfile
      ports:
        - "5432:5432"
      restart: always
      volumes:
        - postgres_data:/var/lib/postgresql/data/
  web:
      build:
        context: ./server
        dockerfile: nodeServer.Dockerfile
      command: npm start
      environment:
        - DB_URL=postgresql://postgres:postgres@db/vehicle_transfer_db
      ports:
        - "8000:8000"
      depends_on:
        - db
  mail:
      build:
        context: ./email
        dockerfile: email/mailServer.Dockerfile
      command: npm start
      ports:
        - "5000:5000"
      depends_on:
        - web
volumes:
  postgres_data: