version: "3"
services: 
  db:
      image: postgres:13
      ports:
        - "5432:5432"
      restart: always
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: vehicle_transfer_db
      volumes:
        - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
        - postgres_data:/var/lib/postgresql/data/
  web:
      build:
        context: .
        dockerfile: nodeServer.Dockerfile
      command: npm start
      environment:
        - DB_URL=postgresql://postgres:postgres@db/vehicle_transfer_db
      ports:
        - "8000:8000"
      depends_on:
        - db
volumes:
  postgres_data: